name: DayJob
version: '${project.version}'
main: com.wamel.dayjob.DayJob
description: This is Day Server Job Plugin
authors:
  - 'WaMel_'

commands:
  jreload:
    description: Hello, DayJob!
  jobreload:
    description: Hello, DayJob!